# 医疗诊断Agent配置

agent:
  name: "LumbarSpineDiagnosticAgent"
  version: "1.0.0"
  description: "腰椎MRI诊断智能助手"
  max_iterations: 5
  timeout: 300  # 秒

models:
  # 视觉理解模型（用于影像分析）
  vision_model: "Qwen/Qwen2-VL-7B-Instruct"
  
  # 语言模型（用于报告生成）
  llm_model: "Qwen/Qwen2.5-7B-Instruct"
  
  # 嵌入模型（用于知识检索）
  embedding_model: "BAAI/bge-large-zh-v1.5"

services:
  # VLLM服务配置
  vllm:
    enabled: true
    gpu_memory_utilization: 0.9
    tensor_parallel_size: 1
    max_model_len: 4096
    dtype: "auto"
  
  # Embedding服务配置
  embedding:
    method: "hf"
    cache_enabled: true
    normalize: true
    batch_size: 32
  
  # 向量数据库配置
  vector_db:
    backend: "sage_db"
    collection_name: "lumbar_spine_cases"
    dimension: 1024
    index_type: "HNSW"
    metric_type: "cosine"
    top_k: 5

image_processing:
  # 图像预处理
  input_size: [512, 512]
  normalization: true
  augmentation: false
  
  # 分割模型
  segmentation:
    model: "SAM"  # Segment Anything Model
    enabled: false  # 如果没有GPU可以禁用
  
  # 特征提取
  feature_extraction:
    method: "clip"  # 或使用医学影像专用模型
    dimension: 768

diagnosis:
  # 诊断阈值
  confidence_threshold: 0.7
  
  # 病变检测
  detection:
    disc_herniation_threshold: 0.8
    degeneration_threshold: 0.6
  
  # 报告生成
  report:
    include_similar_cases: true
    max_similar_cases: 5
    include_confidence_score: true
    language: "zh"

knowledge_base:
  # 知识来源
  sources:
    - "medical_literature"
    - "clinical_guidelines"
    - "case_database"
  
  # 更新策略
  update_frequency: "weekly"
  auto_update: false

output:
  # 输出格式
  format: "structured"  # structured, json, pdf
  save_path: "output/diagnoses/"
  
  # 包含内容
  include_image_annotations: true
  include_similar_cases: true
  include_references: true

logging:
  level: "INFO"
  save_logs: true
  log_path: "logs/medical_diagnosis/"
