"""Serving integration boundary for SAGE.

This package intentionally does not implement an inference engine.
Instead, it standardizes how SAGE integrates with the independent
`isagellm` engine family.
"""

from .gateway import (
    GatewayProbeResult,
    SageServeConfig,
    build_sagellm_gateway_command,
    default_gateway_config,
    ensure_sagellm_model,
    gateway_health_url,
    gateway_openai_base_url,
    infer_module_availability,
    probe_gateway,
)
from .integrations import (
    COMFY_FIRST_EXTENSION_POINT,
    LANGGRAPH_SECOND_EXTENSION_POINT,
    WORKFLOW_INTEGRATION_SCHEMA_VERSION,
    ImportedWorkflow,
    MockSageExecutable,
    MockWorkflowProductAdapter,
    WorkflowExecutionTarget,
    WorkflowExecutionTargetType,
    WorkflowImportRequest,
    WorkflowImportResponse,
    WorkflowIntegrationExtensionPoint,
    WorkflowIntegrationOperation,
    WorkflowIntegrationRegistry,
    WorkflowIntegrationRequest,
    WorkflowIntegrationResponse,
    WorkflowJobResultCollectRequest,
    WorkflowJobResultCollectResponse,
    WorkflowJobStatus,
    WorkflowJobStatusPollRequest,
    WorkflowJobStatusPollResponse,
    WorkflowJobSubmitRequest,
    WorkflowJobSubmitResponse,
    WorkflowProductAdapter,
    WorkflowProductAdapterDescriptor,
    WorkflowServingRequestContext,
    WorkflowSubmitMode,
    default_workflow_product_extension_points,
    validate_workflow_product_adapter,
)

__all__ = [
    "SageServeConfig",
    "GatewayProbeResult",
    "default_gateway_config",
    "gateway_health_url",
    "gateway_openai_base_url",
    "build_sagellm_gateway_command",
    "infer_module_availability",
    "probe_gateway",
    "ensure_sagellm_model",
    "WORKFLOW_INTEGRATION_SCHEMA_VERSION",
    "COMFY_FIRST_EXTENSION_POINT",
    "LANGGRAPH_SECOND_EXTENSION_POINT",
    "WorkflowIntegrationOperation",
    "WorkflowExecutionTargetType",
    "WorkflowJobStatus",
    "WorkflowSubmitMode",
    "WorkflowIntegrationExtensionPoint",
    "WorkflowProductAdapterDescriptor",
    "WorkflowIntegrationRequest",
    "WorkflowIntegrationResponse",
    "WorkflowServingRequestContext",
    "WorkflowExecutionTarget",
    "ImportedWorkflow",
    "WorkflowImportRequest",
    "WorkflowImportResponse",
    "WorkflowJobSubmitRequest",
    "WorkflowJobSubmitResponse",
    "WorkflowJobStatusPollRequest",
    "WorkflowJobStatusPollResponse",
    "WorkflowJobResultCollectRequest",
    "WorkflowJobResultCollectResponse",
    "WorkflowProductAdapter",
    "WorkflowIntegrationRegistry",
    "MockSageExecutable",
    "MockWorkflowProductAdapter",
    "default_workflow_product_extension_points",
    "validate_workflow_product_adapter",
]
