#!/bin/bash
# SAGE Environment Activation Script (Full Setup)
# Generated by SAGE installer

echo "🐳 Connecting to SAGE Docker container..."
echo "Container: container_setup-sage-1"

if command -v docker &> /dev/null; then
    CONTAINER_NAME="container_setup-sage-1"
    
    if [ -n "$CONTAINER_NAME" ]; then
        echo "✅ Connecting to container: $CONTAINER_NAME"
        echo "🔧 Activating SAGE environment in Docker..."
        echo ""
        echo "📋 You will be dropped into Docker with (sage) conda environment active"
        echo "💡 Type 'exit' to return to your host system"
        echo ""
        
        # Execute docker with proper conda activation and persistent environment
        docker exec -it "$CONTAINER_NAME" bash -c '
            source /opt/conda/etc/profile.d/conda.sh
            conda activate sage
            echo "✅ SAGE environment activated successfully!"
            echo "📝 You are now in the (sage) environment inside Docker"
            echo "🚀 Test with: python -c \"import sage\""
            echo ""
            export PS1="(sage) \u@\h:\w# "
            exec bash --norc --noprofile
        '
    else
        echo "❌ No SAGE Docker container found"
        echo "💡 Try: docker ps"
        echo "💡 Or: ssh root@localhost -p 2222"
    fi
else
    echo "❌ Docker not found"
    echo "💡 Alternative: ssh root@localhost -p 2222"
fi
