#!/bin/bash
# SAGE Environment Activation Script (Minimal Setup)
# Generated by SAGE installer

echo "🔧 Activating SAGE conda environment..."

# Initialize conda if not already initialized
if ! command -v conda &> /dev/null; then
    echo "❌ Conda not found in PATH"
    echo "💡 Please ensure conda is installed and in your PATH"
    return 1 2>/dev/null || exit 1
fi

# Initialize conda for this shell session
eval "$(conda shell.bash hook)" 2>/dev/null || {
    echo "🔧 Initializing conda for bash..."
    conda init bash
    echo "📝 Conda initialized. Please restart your shell or run 'source ~/.bashrc'"
    echo "📝 Then run this script again: source ./activate_sage.sh"
    return 1 2>/dev/null || exit 1
}

# Activate the sage environment
conda activate sage

if [ $? -eq 0 ]; then
    echo "✅ SAGE environment activated successfully!"
    echo "📝 You are now in the (sage) environment"
    echo "🚀 Test with: python -c \"import sage; print('SAGE ready!')\""
    echo "💡 Type 'conda deactivate' to exit this environment"
    echo ""
else
    echo "❌ Failed to activate SAGE environment"
    echo "💡 Try: conda env list"
    return 1 2>/dev/null || exit 1
fi
