# SAGE 项目统一配置文件
# 这个文件包含了所有包共享的元数据信息

[project]
# 组织信息
organization = "IntelliStream"
team_name = "IntelliStream Team"
contact_email = "intellistream@outlook.com"

# 项目信息
project_name = "SAGE"
project_description = "Smart Analytics and Graph Engine"
package_prefix = "intellistream-sage"  # PyPI包名前缀
license = "MIT"  # 许可证

# Python 版本要求
python_requires = ">=3.10"
python_versions = ["3.10", "3.11", "3.12"]

# URLs (统一管理所有链接)
[urls]
homepage = "https://github.com/intellistream/SAGE"
repository = "https://github.com/intellistream/SAGE.git"
documentation = "https://intellistream.github.io/SAGE-Pub/"
issues = "https://github.com/intellistream/SAGE/issues"
changelog = "https://github.com/intellistream/SAGE/releases"

# 通用分类器
[classifiers]
items = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Distributed Computing",
]

# 版本管理
[versions]
# 主版本号，所有包统一使用
major = "1"
minor = "0"
patch = "1"
current = "1.0.1"

# 包名映射 (PyPI名称 -> 目录路径)
[packages]
"intellistream-sage" = "packages/sage-core"
"intellistream-sage-kernel" = "packages/sage-kernel"
"intellistream-sage-middleware" = "packages/sage-middleware"
"intellistream-sage-userspace" = "packages/sage-userspace"
"intellistream-sage-dev-toolkit" = "packages/sage-dev-toolkit"
"intellistream-sage-frontend" = "packages/sage-frontend"
"intellistream-sage-cli" = "packages/sage-cli"

# 包描述
[package_descriptions]
"intellistream-sage" = "SAGE Framework Meta Package"
"intellistream-sage-kernel" = "SAGE Framework - 统一内核 (Core + Runtime + Utils + CLI)"
"intellistream-sage-middleware" = "SAGE Framework - 中间件组件 (包含 LLM 中间件服务)"
"intellistream-sage-userspace" = "SAGE Framework - 用户空间组件 (合并 sage-lib, sage-plugins 和 sage-examples)"
"intellistream-sage-dev-toolkit" = "SAGE Framework Development Toolkit - Unified development tools for SAGE project"
"intellistream-sage-frontend" = "SAGE Framework - Web Frontend and Dashboard Interface"
"intellistream-sage-cli" = "SAGE Framework - 命令行工具包，提供集群管理、作业部署和配置管理功能"

# 关键词
[keywords]
common = ["sage", "framework", "intellistream", "ai", "ml", "data"]
kernel = ["rag", "llm", "dataflow", "reasoning", "framework", "cli", "kernel"]
middleware = ["rag", "llm", "middleware", "service", "api", "dataflow", "reasoning", "framework"]
userspace = ["rag", "llm", "library", "plugins", "components", "algorithms", "extensions", "ecosystem"]
dev_toolkit = ["development", "tools", "cli", "testing", "linting", "formatting", "utilities"]
frontend = ["web", "frontend", "dashboard", "fastapi", "angular", "ui", "visualization"]
platform = ["stream processing", "real-time", "data streams", "analytics", "machine learning"]
