[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sage"
version = "1.0.0"
description = "SAGE - Streaming Analytics and Graph Engine"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "SAGE Team", email = "team@sage.com"},
]
license = {text = "Apache-2.0"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

# 核心依赖 - 安装本地包
dependencies = [
    "intsage-kernel",
    "intsage-middleware", 
    "intsage-userspace",
    "intsage-dev-toolkit",
]

[project.optional-dependencies]
# 开发依赖
dev = [
    "pytest>=7.0",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-benchmark",
    "black",
    "isort",
    "flake8",
    "mypy",
    "ipython",
    "jupyter",
    "intsage-dev-toolkit",
]

# 文档依赖
docs = [
    "sphinx",
    "sphinx-rtd-theme",
]

[project.scripts]
sage-license = "scripts.sage_license:main"

[project.urls]
Homepage = "https://github.com/intellistream/SAGE"
Repository = "https://github.com/intellistream/SAGE"
Documentation = "https://sage.readthedocs.io/"
"Bug Reports" = "https://github.com/intellistream/SAGE/issues"

[tool.setuptools]
# 元包配置
packages = ["sage"]
include-package-data = true

[tool.setuptools.package-dir]
sage = "packages/sage/src/sage"
