[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sage"
version = "0.1.0"
description = "SAGE - Streaming Analytics and Graph Engine with Core API"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "SAGE Team", email = "team@sage.com"},
]
license = {text = "Apache-2.0"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

# 核心依赖 - 安装本地包
dependencies = [
    "intsage-kernel",
    "intsage-middleware", 
    "intsage-dev-toolkit",
]

[project.optional-dependencies]
# Commercial/Enterprise Edition (requires license)
enterprise = [
    "intsage-kernel[enterprise]",
    "intsage-middleware[enterprise]", 
]

# 开发依赖
dev = [
    "pytest>=7.0",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-benchmark",
    "black",
    "isort",
    "flake8",
    "mypy",
    "ipython",
    "jupyter",
    "intsage-dev-toolkit",
]

# 文档依赖
docs = [
    "sphinx",
    "sphinx-rtd-theme",
]

# All features combined
all = [
    "sage[enterprise]",
    "sage[dev]",
    "sage[docs]",
]

[project.scripts]
sage-license = "tools.license.sage_license:main"
sage-enterprise = "tools.enterprise.enterprise_manager:main"

[project.urls]
Homepage = "https://github.com/intellistream/SAGE"
Repository = "https://github.com/intellistream/SAGE"
Documentation = "https://sage.readthedocs.io/"
"Bug Reports" = "https://github.com/intellistream/SAGE/issues"

[tool.setuptools]
# 元包配置 - 主要依赖于子包，同时提供统一入口点
packages = ["sage"]
include-package-data = true

[tool.setuptools.package-dir]
sage = "packages/sage/src/sage"
