[build-system]
requires = ["setuptools>=61.0", "wheel", "Cython>=0.29.0", "pybind11>=2.6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sage-stream"
version = "0.1.2"
authors = [
    {name = "IntelliStream", email = "intellistream@outlook.com"}
]
description = "SAGE - Stream Processing Framework for python-native distributed systems with JobManager"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers", 
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: C++",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Distributed Computing",
]
keywords = ["stream-processing", "distributed-computing", "jobmanager", "sage"]

dependencies = [
    "accelerate>=0.29.3",
    "einops",
    "outlines",
    "sentencepiece", 
    "tiktoken",
    "torchvision<=0.20.1,>=0.15.0",
    "psutil",
    "aioboto3==14.1.0",
    "aiohttp==3.10.9",
    "cohere==5.15.0",
    "faiss-cpu==1.9.0",
    "fastapi==0.115.12",
    "feedparser==6.0.11",
    "fitz==0.0.1.dev2",
    "h11==0.14.0",
    "httpx==0.28.1",
    "InstructorEmbedding==1.0.1",
    "Jinja2==3.1.6",
    "numpy==1.26.4",
    "openai",
    "opencv_python_headless==4.10.0.84",
    "Pillow",
    "pipmaster==0.5.1",
    "pydantic==2.11.5",
    "pytest==7.4.4",
    "python-dotenv==1.1.0",
    "PyYAML==6.0.2",
    "Requests==2.32.4",
    "rouge==1.0.1",
    "scikit_learn==1.7.0",
    "scipy==1.15.3",
    "sentence_transformers==3.1.1",
    "sympy>=1.12",
    "bm25s==0.2.13",
    "PyStemmer==3.0.0",
    "tenacity==9.0.0",
    "torch==2.4.0",
    "transformers==4.45.2",
    "typeguard==4.3.0",
    "uvicorn==0.34.3",
    "zhipuai==2.1.5.20250526",
    "ray[default]==2.37.0",
    "python-multipart>=0.0.6",
    "huggingface_hub>=0.22.2",
    "kafka-python>=2.2.0",
    "dill>=0.3.8",
    "tabulate>=0.9.0",
    "colorama>=0.4.6",
    "rank_bm25",
    "tqdm",
    "typer>=0.9.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.4",
    "pytest-cov",
    "pytest-html",
    "pytest-xdist",
    "black",
    "flake8",
    "mypy"
]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "myst-parser"
]

[project.urls]
Homepage = "https://github.com/intellistream/SAGE"
Repository = "https://github.com/intellistream/SAGE"
Documentation = "https://github.com/intellistream/SAGE/docs"
"Bug Tracker" = "https://github.com/intellistream/SAGE/issues"

[project.scripts]
sage = "sage.cli.main:app"
sage-jm = "sage.cli.job:app"

[tool.setuptools]
packages = ["sage", "sage_ext"]

[tool.setuptools.package-data]
"sage.core" = ["config/*.yaml"]
"sage_deployment" = ["scripts/*.sh", "templates/*"]

[tool.setuptools.exclude-package-data]
"*" = ["tests", "test*", "*test*", "*.tests.*"]

# Cython 配置
[tool.cython-lint]
max-line-length = 88

# Black 代码格式化配置
[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''
