# SAGE Meta Package Configuration  
# 这个文件用于：
# 1. 开发者安装: pip install -e . (使用本地源码)
# 2. PyPI发布: 需要临时修改dependencies为PyPI包名
# 注意：quickstart.sh 不使用这个文件，而是直接安装各个子包

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "isage"
version = "0.1.4"
description = "SAGE - Streaming-Augmented Generative Execution"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "SAGE Team", email = "shuhao_zhang@hust.edu.cn"},
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",]

# 核心依赖 - 开发时使用本地路径
dependencies = [
    "isage-kernel @ file:./packages/sage-kernel",
    "isage-middleware @ file:./packages/sage-middleware", 
    "isage-libs @ file:./packages/sage-libs",
    "isage-common @ file:./packages/sage-common",
]

[project.optional-dependencies]
# PyPI发布版本 - 使用PyPI包名（用于构建发布包时）
pypi = [
    "isage-kernel",
    "isage-middleware", 
    "isage-libs", 
    "isage-common",
]

# 开发依赖 - 使用本地包
dev-local = [
    "isage-kernel @ file:./packages/sage-kernel",
    "isage-middleware @ file:./packages/sage-middleware", 
    "isage-libs @ file:./packages/sage-libs",
    "isage-common @ file:./packages/sage-common",
    # 开发工具
    "pytest>=6.0",
    "pytest-asyncio",
    "pytest-cov",
    "black",
    "ruff",
    "mypy",
]

# Commercial/Enterprise Edition (requires license)
enterprise = [
    "isage-kernel[enterprise]",
    "isage-middleware[enterprise]", 
]

# 基础工具包 (包含CLI)
basic = [
    "isage-common[cli]",
]

# 开发依赖
dev = [
    "pytest>=7.0",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-benchmark",
    "black",
    "isort",
    "flake8",
    "mypy",
    "ipython",
    "jupyter",
    "isage-common[dev]",
]

# 前端功能
frontend = [
    "isage-common[frontend]",
]

# 文档依赖
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "isage-common[docs]",
]

# All features combined
all = [
    "isage[enterprise]",
    "isage[basic]",
    "isage[frontend]",
    "isage[dev]",
    "isage[docs]",
]

[project.scripts]
# 主CLI命令 - 由sage-common提供
sage = "sage.common.cli.main:app"
sage-cli = "sage.common.cli.main:app"

# 核心工具由各自的包提供，这里只是确保环境正确
# sage-core, sage-dev, sage-server, sage-install 由 sage-common 提供
# sage-kernel 由 sage-kernel 包提供
# sage-examples 由 sage-libs 包提供
# sage-jobmanager 由 sage-common 提供

# 企业版和许可证管理工具
sage-license = "tools.license.sage_license:main"
sage-enterprise = "tools.enterprise.enterprise_manager:main"

[project.urls]
Homepage = "https://github.com/intellistream/SAGE"
Repository = "https://github.com/intellistream/SAGE"
Documentation = "https://sage.readthedocs.io/"
"Bug Reports" = "https://github.com/intellistream/SAGE/issues"

[tool.setuptools]
# 元包配置 - 主要依赖于子包，同时提供统一入口点
packages = ["sage"]
include-package-data = true

[tool.setuptools.package-dir]
sage = "packages/sage/src/sage"


# SAGE 项目自定义配置
[tool.sage]
# 如果将来需要项目特定的配置，可以在这里添加
# 目前所有必要的配置都已经在标准的 [project] 区域中定义
