"""
Kernel 共享常量

定义了 sage-kernel 中使用的常量。
"""

# 默认配置
DEFAULT_CHECKPOINT_INTERVAL = 60  # 秒
DEFAULT_HEALTH_CHECK_INTERVAL = 30  # 秒
DEFAULT_MAX_RESTART_ATTEMPTS = 3
DEFAULT_CLEANUP_TIMEOUT = 5.0  # 秒

# 重启策略
RESTART_STRATEGY_FIXED = "fixed_delay"
RESTART_STRATEGY_EXPONENTIAL = "exponential_backoff"
RESTART_STRATEGY_FAILURE_RATE = "failure_rate"

# 放置策略
PLACEMENT_STRATEGY_SIMPLE = "simple"
PLACEMENT_STRATEGY_RESOURCE_AWARE = "resource_aware"
PLACEMENT_STRATEGY_LOAD_BALANCE = "load_balance"

# 调度策略
SCHEDULING_STRATEGY_FIFO = "fifo"
SCHEDULING_STRATEGY_PRIORITY = "priority"
SCHEDULING_STRATEGY_RESOURCE_AWARE = "resource_aware"

__all__ = [
    "DEFAULT_CHECKPOINT_INTERVAL",
    "DEFAULT_HEALTH_CHECK_INTERVAL",
    "DEFAULT_MAX_RESTART_ATTEMPTS",
    "DEFAULT_CLEANUP_TIMEOUT",
    "RESTART_STRATEGY_FIXED",
    "RESTART_STRATEGY_EXPONENTIAL",
    "RESTART_STRATEGY_FAILURE_RATE",
    "PLACEMENT_STRATEGY_SIMPLE",
    "PLACEMENT_STRATEGY_RESOURCE_AWARE",
    "PLACEMENT_STRATEGY_LOAD_BALANCE",
    "SCHEDULING_STRATEGY_FIFO",
    "SCHEDULING_STRATEGY_PRIORITY",
    "SCHEDULING_STRATEGY_RESOURCE_AWARE",
]
