name: 'Setup SAGE'
description: 'Install SAGE framework with all dependencies'
author: 'SAGE Team'

inputs:
  install-mode:
    description: 'Installation mode: core, standard, or dev'
    required: false
    default: 'dev'
  python-version:
    description: 'Python version to use (only for GitHub-hosted runners)'
    required: false
    default: '3.11'
  skip-system-deps:
    description: 'Skip system dependency installation (for self-hosted runners with pre-installed deps)'
    required: false
    default: 'false'
  hf-token:
    description: 'HuggingFace token'
    required: false
    default: ''
  create-env-file:
    description: 'Create .env file with provided secrets'
    required: false
    default: 'false'
  env-file-content:
    description: 'Content for .env file (base64 encoded to handle multiline)'
    required: false
    default: ''

outputs:
  sage-version:
    description: 'Installed SAGE version'
    value: ${{ steps.verify.outputs.version }}
  cpp-extensions-available:
    description: 'Whether C++ extensions are available'
    value: ${{ steps.verify.outputs.cpp_extensions }}

runs:
  using: 'composite'
  steps:
    # Step 1: Setup Python (skip for self-hosted if Python already available)
    - name: Setup Python (GitHub-hosted runners)
      if: ${{ !contains(runner.name, 'self-hosted') && runner.os != 'self-hosted' }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    # Step 2: Install System Dependencies
    - name: Install System Dependencies
      if: ${{ inputs.skip-system-deps != 'true' }}
      shell: bash
      run: |
        echo "ðŸ”§ Installing system dependencies..."

        # Check if we need to install (self-hosted may have them)
        need_install=false
        for cmd in cmake pkg-config; do
          if ! command -v $cmd &> /dev/null; then
            need_install=true
            break
          fi
        done

        if [ "$need_install" = "true" ]; then
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            cmake \
            pkg-config \
            libopenblas-dev \
            liblapack-dev \
            git
          echo "âœ… System dependencies installed"
        else
          echo "âœ… System dependencies already available"
        fi

    # Step 3: Verify Submodules
    - name: Verify Submodules
      shell: bash
      run: |
        echo "ðŸ” Verifying Git submodules..."
        git submodule status

        echo ""
        echo "Checking critical submodule directories:"
        all_ok=true
        for submodule in \
          "packages/sage-middleware/src/sage/middleware/components/sage_db/sageDB" \
          "packages/sage-middleware/src/sage/middleware/components/sage_flow/sageFlow" \
          "packages/sage-middleware/src/sage/middleware/components/sage_tsdb/sageTSDB"; do
          if [ -d "$submodule" ] && [ -n "$(ls -A "$submodule" 2>/dev/null)" ]; then
            echo "âœ… $submodule - OK"
          else
            echo "âš ï¸  $submodule - Missing or empty"
            all_ok=false
          fi
        done

        if [ "$all_ok" = "false" ]; then
          echo ""
          echo "âš ï¸  Some submodules not properly initialized"
          echo "ðŸ’¡ C++ extension build may skip related components"
        fi

    # Step 4: Create .env file (optional)
    - name: Create Environment File
      if: ${{ inputs.create-env-file == 'true' }}
      shell: bash
      run: |
        if [ -n "${{ inputs.env-file-content }}" ]; then
          echo "${{ inputs.env-file-content }}" | base64 -d > .env
          echo "âœ… .env file created from provided content"
        else
          # Create minimal .env
          cat > .env << EOF
        # SAGE Environment Configuration (auto-generated)
        HF_TOKEN=${{ inputs.hf-token }}
        HF_ENDPOINT=https://hf-mirror.com
        SAGE_TEST_MODE=true
        SAGE_LOG_LEVEL=INFO
        EOF
          echo "âœ… Minimal .env file created"
        fi

    # Step 5: Install SAGE
    - name: Install SAGE
      shell: bash
      run: |
        echo "ðŸš€ Installing SAGE (${{ inputs.install-mode }} mode)..."

        # Ensure ~/.local/bin is in PATH for pip-installed CLI tools
        export PATH="$HOME/.local/bin:$PATH"

        # Make PATH persistent for subsequent steps in workflow
        echo "$HOME/.local/bin" >> $GITHUB_PATH

        # Make scripts executable
        chmod +x ./tools/install/core/ci_install_wrapper.sh
        chmod +x ./quickstart.sh

        # Run installation
        ./tools/install/core/ci_install_wrapper.sh --${{ inputs.install-mode }} --yes

        echo "âœ… SAGE installation completed"

    # Step 6: Verify Installation
    - name: Verify Installation
      id: verify
      shell: bash
      run: |
        export PATH="$HOME/.local/bin:$PATH"

        echo "ðŸ” Verifying SAGE installation..."

        # Check SAGE import and version
        SAGE_VERSION=$(python -c "import sage; print(sage.__version__)" 2>/dev/null || echo "unknown")
        echo "version=$SAGE_VERSION" >> $GITHUB_OUTPUT
        echo "âœ… SAGE version: $SAGE_VERSION"

        # Check imports
        python -c "import sage; import sage.common; import sage.kernel" && echo "âœ… Core imports OK"

        # Check CLI
        if command -v sage-dev >/dev/null 2>&1 || [ -x "$HOME/.local/bin/sage-dev" ]; then
          echo "âœ… sage-dev CLI available"
        else
          echo "âš ï¸  sage-dev not in PATH (may need to source environment)"
        fi

        # Check C++ extensions
        CPP_EXT="false"
        so_files=$(find packages/sage-middleware/src/sage/middleware/components/ \
          \( -name "_sage_*.so" -o -name "*.cpython-*.so" \) -type f 2>/dev/null || true)
        if [ -n "$so_files" ]; then
          CPP_EXT="true"
          echo "âœ… C++ extensions available"
        else
          echo "âš ï¸  C++ extensions not found"
        fi
        echo "cpp_extensions=$CPP_EXT" >> $GITHUB_OUTPUT

        echo ""
        echo "ðŸŽ‰ SAGE setup completed successfully!"
