source:
  data_path: "./examples/data/queries.jsonl"  # 修正相对路径
  platform: "local"

retriever:
  # ChromaDB 专用配置
  dimension: 384    # 修改为与 HuggingFace all-MiniLM-L6-v2 匹配
  top_k: 2
  
  chroma:
    persistence_path: "./examples/rag/chroma_qa_database"
    collection_name: "qa_knowledge_base"
    use_embedding_query: true
    
    # 知识库已预加载，注释掉自动加载
    # knowledge_file: "../../data/qa_knowledge_base.txt"
    
    # ChromaDB 元数据配置 (简化格式)
    metadata:
      hnsw:space: "cosine"           # 距离度量
  
  # 嵌入模型配置
  embedding:
    method: "hf"
    model: "sentence-transformers/all-MiniLM-L6-v2"

promptor:
  template: |
    基于以下检索到的相关文档，回答用户问题：
    
    相关文档：
    {external_corpus}
    
    请提供准确、有用的回答。

generator:
  local:
    method: "hf"
    model_name: "mistralai/Mistral-7B-Instruct-v0.1"
    seed: 42

sink:
  enable_log: true

