pipeline:
  name: "sage-api-operator-operator_test"
  description: "Test pipeline for Sage API Operator"
  version: "1.0.0"

source:
  # 数据源类型：'local'（本地 JSONL） 或 'hf'（HuggingFace Dataset）
  type: "hf"
  # 本地 JSONL 文件路径（type=local 时生效）
  data_path: "examples/data/sample/evaluate.json"

  # HuggingFace Dataset 参数（type=hf 时生效）
  hf_dataset_name:   "RUC-NLPIR/FlashRAG_datasets"
  hf_dataset_config: "asqa"
  hf_split:          "dev"

retriever:
  # 检索器类型选择: 'chroma' 或 'wiki18_faiss'
  type: "wiki18_faiss"  # 使用Wiki18 FAISS检索器
  
  # 通用配置
  dimension: 1024    # BGE-M3模型的维度
  top_k: 8
  
  # Wiki18 FAISS 专用配置 (type=wiki18_faiss 时生效)
  faiss:
    index_path: "/home/cyb/wiki18_fulldoc_bgem3_index.index"
    documents_path: "/home/cyb/wiki18_fulldoc.jsonl"
  
  # 嵌入模型配置
  embedding:
    method: "hf"
    model: "BAAI/bge-m3"  # 使用BGE-M3模型进行Wiki18 FAISS检索
    gpu_device: 0  # 明确指定BGE-M3使用GPU 0

generator:
  local:
    method: "hf"
    model_name: "meta-llama/Llama-2-13b-chat-hf"
    seed: 42

  vllm:
    api_key: "token-abc123"
    method: "openai"
    model_name: "meta-llama/Llama-2-7b-chat-hf"
    base_url: "http://sage3:8000/v1"
    seed: 42

  remote:
    api_key: ""
    method: "openai"
    model_name: "qwen-turbo-0919"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    seed: 42

promptor:
  platform: "local"

sink:
  platform: "local"

refiner:
  base_model_path: "Qwen/Qwen2.5-3B-Instruct"
  query_analysis_module_lora_path: "jinjiajie/Query-Analysis-Qwen2.5-3B-Instruct"
  doc_structuring_module_lora_path: "jinjiajie/Doc-Structuring-Qwen2.5-3B-Instruct"
  global_selection_module_lora_path: "jinjiajie/Global-Selection-Qwen2.5-3B-Instruct"
  score_model_name: "bge-reranker-v2-m3"
  score_model_path: "BAAI/bge-reranker-v2-m3"
  max_model_len: 25000
  budget: 2048
  gpu_device: 1  # vLLM使用GPU 1
  score_gpu_device: 1  # score模型使用GPU 0
  gpu_memory_utilization: 0.7

evaluate:
  platform: "local"