pipeline:
  name: "sage-api-operator-operator_test"
  description: "Test pipeline for Sage API Operator"
  version: "1.0.0"

source:
  # data_path: "sample/one_question.txt"
  data_path: "examples/data/sample/question.txt"
  platform: "local"

retriever:
  # ChromaDB 专用配置
  dimension: 384    # 修改为与 HuggingFace all-MiniLM-L6-v2 匹配
  top_k: 2
  
  chroma:
    persistence_path: "./examples/rag/chroma_qa_database"
    collection_name: "qa_knowledge_base"
    use_embedding_query: true
    
    # 知识库已预加载，注释掉自动加载
    # knowledge_file: "../../data/qa_knowledge_base.txt"
    
    # ChromaDB 元数据配置 (简化格式)
    metadata:
      hnsw:space: "cosine"           # 距离度量
  
  # 嵌入模型配置
  embedding:
    method: "hf"
    model: "sentence-transformers/all-MiniLM-L6-v2"

reranker:
  platform: "local"
  model_name: "BAAI/bge-reranker-v2-m3"
  top_k: 3

refiner:
  platform: "local"
  method: "openai"
  model_name: "qwen-turbo-0919"
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  api_key: ""
  seed: 42

generator:
  local:
    method: "hf"
    model_name: "meta-llama/Llama-2-13b-chat-hf"
    seed: 42

  vllm:
    api_key: "token-abc123"
    method: "openai"
    model_name: "meta-llama/Llama-2-13b-chat-hf"
    base_url: "http://sage3:8000/v1"
    seed: 42

  remote:
    api_key: ""
    method: "openai"
    model_name: "qwen-turbo-0919"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    seed: 42

writer:

promptor:
  platform: "local"

sink_true:
  file_path: "output_true.txt"


sink_false:
  file_path: "output_false.txt"


sink_terminal: