#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import subprocess
from importlib import metadata
from pathlib import Path
from typing import Any

import yaml


def _normalize_distribution_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", str(name or "").strip().lower())


def _editable_distribution_names() -> set[str]:
    names: set[str] = set()
    for distribution in metadata.distributions():
        try:
            direct_url_text = distribution.read_text("direct_url.json")
        except Exception:
            direct_url_text = None
        if not direct_url_text:
            continue
        try:
            payload = json.loads(direct_url_text)
        except json.JSONDecodeError:
            continue
        dir_info = payload.get("dir_info") if isinstance(payload, dict) else None
        if not isinstance(dir_info, dict) or not bool(dir_info.get("editable")):
            continue
        raw_name = (
            distribution.metadata.get("Name")
            if distribution.metadata is not None
            else distribution.name
        )
        normalized_name = _normalize_distribution_name(raw_name)
        if normalized_name:
            names.add(normalized_name)
    return names


def _requirement_name(token: str) -> str:
    head = re.split(r"\s|\[|<|>|=|!|~|;", token, maxsplit=1)[0]
    return _normalize_distribution_name(head)


def _filter_pip_dependencies(items: list[Any], *, editable_names: set[str]) -> list[str]:
    filtered: list[str] = []
    for item in items:
        if not isinstance(item, str):
            continue
        token = item.strip()
        lower = token.lower()
        if not token:
            continue
        if lower.startswith("-e "):
            continue
        if lower.startswith("file://"):
            continue
        if lower.startswith("/"):
            continue
        if " @ file://" in lower:
            continue
        if _requirement_name(token) in editable_names:
            continue
        filtered.append(token)
    return filtered


def export_runtime_environment(env_name: str) -> tuple[dict[str, Any], list[str]]:
    command = ["conda", "env", "export", "-n", env_name]
    result = subprocess.run(command, check=True, capture_output=True, text=True)
    payload = yaml.safe_load(result.stdout)
    if not isinstance(payload, dict):
        raise RuntimeError("conda env export did not produce a mapping/object")

    payload.pop("prefix", None)
    payload["name"] = env_name
    editable_names = _editable_distribution_names()
    pip_dependencies: list[str] = []

    dependencies = payload.get("dependencies")
    if isinstance(dependencies, list):
        normalized_dependencies: list[Any] = []
        for entry in dependencies:
            if isinstance(entry, dict) and isinstance(entry.get("pip"), list):
                filtered_pip = _filter_pip_dependencies(
                    list(entry["pip"]),
                    editable_names=editable_names,
                )
                pip_dependencies.extend(filtered_pip)
                continue
            normalized_dependencies.append(entry)
        payload["dependencies"] = normalized_dependencies
    return payload, pip_dependencies


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Export the current conda runtime environment into a Docker-friendly lock file."
        )
    )
    parser.add_argument("--env-name", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    output_path = Path(args.output).expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pip_output_path = output_path.with_suffix(".pip.txt")

    payload, pip_dependencies = export_runtime_environment(str(args.env_name))
    rendered = yaml.safe_dump(payload, sort_keys=False, allow_unicode=False)
    header = "# Generated by docker/cluster8/scripts/export_runtime_env_lock.py\n"
    output_path.write_text(header + rendered, encoding="utf-8")
    pip_output_path.write_text(
        "\n".join(pip_dependencies) + ("\n" if pip_dependencies else ""), encoding="utf-8"
    )
    print(output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
