[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sage-core"
version = "1.0.0"
description = "SAGE Framework - 核心框架"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "IntelliStream Team", email = "sage@intellistream.cc"},
]
keywords = ["rag", "llm", "dataflow", "reasoning", "framework"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
    "sage-utils",  # 依赖工具包
    # Core ML/AI dependencies
    "accelerate>=0.29.3",
    "einops",
    "outlines",
    "sentencepiece",
    "tiktoken",
    "torchvision<=0.20.1,>=0.15.0",
    "torch==2.4.0",
    "transformers==4.45.2",
    "sentence_transformers==3.1.1",
    "InstructorEmbedding==1.0.1",
    "huggingface_hub>=0.22.2",
    "peft",
    "vllm",
    
    # System and utilities
    "psutil",
    "numpy>=2.2.6",
    "pandas>=1.3.0",
    "scipy==1.15.3",
    "scikit_learn==1.7.0",
    "sympy>=1.12",
    "Cython",
    "pybind11",
    
    # Web and API
    "aioboto3==14.1.0",
    "fastapi==0.115.12",
    "uvicorn==0.34.3",
    "python-multipart>=0.0.6",
    "h11==0.14.0",
    "httpx==0.28.1",
    "Requests==2.32.4",
    "socksio>=1.0.0",
    "aiohttp>=3.12.15",
    "aiohappyeyeballs>=2.6.1",
    "aiosignal>=1.4.0",

    # Data processing and storage
    "zhipuai>=2.1.5",
    "aioboto3==15.0.0",
    "cohere>=5.15.0",
    "bm25s>=0.2.13",
    "snowballstemmer>=3.0.1",
    # LLM Services
    "cohere==5.15.0",
    "openai",
    "ollama",
    "zhipuai==2.1.5.20250526",
    
    # Search and retrieval
    "faiss-cpu==1.9.0",
    "bm25s==0.2.13",
    "rank_bm25",
    "PyStemmer==3.0.0",
    
    # Text and document processing
    "feedparser==6.0.11",
    "beautifulsoup4",
    "nltk",
    "rouge==1.0.1",
    "dill>=0.3.8",
    # Image processing
    "fitz==0.0.1.dev2",
    "opencv_python_headless==4.10.0.84",
    "Pillow",
    
    # Configuration and data
    "pydantic",
    "PyYAML==6.0.2",
    "python-dotenv==1.1.0",
    "Jinja2==3.1.6",
    "json_repair",
    
    # Distributed computing
    "ray[default]==2.37.0",
    "kafka-python>=2.2.0",
    "dill>=0.3.8",
    
    # CLI and utilities
    "typer",
    "rich>=13.0.0",
    "tqdm",
    "tabulate>=0.9.0",
    "colorama>=0.4.6",
    "watchdog>=2.1.5,<7",
    
    # Package management and validation
    "pipmaster==0.5.1",
    "typeguard==4.3.0",
    "tenacity==9.0.0",
    
    # Development and testing (moved to optional-dependencies but keeping some core ones)
    "pytest==7.4.4",
    "pytest-mock",
    "datasets",
    "execnet",
    "pytest-asyncio",
    "pytest-benchmark",
    "pytest-xdist",


    # Legacy dependencies to maintain compatibility
    "aiofiles>=0.8.0",
    "ascii_colors>=0.10.0",
    "wcwidth>=0.2.13",
    "chromadb>=0.4.0",
    "redis>=4.5.0",
]

[project.optional-dependencies]
# 扩展支持
extensions = ["sage-extensions"]
# 插件支持  
plugins = ["sage-plugins"]
# 服务支持
service = ["sage-service"]
# 完整功能
full = ["sage-extensions", "sage-plugins", "sage-service"]

# 开发依赖
dev = [
    "pytest>=7.0.0",
    #     "pytest-cov>=4.0.0" # Coverage disabled,
    "pytest-asyncio>=0.21.0",
    "pytest-mock>=3.10.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "mypy>=1.0.0",
    "ruff>=0.1.0",
    "pre-commit>=3.0.0",
    "build>=0.10.0",
]

# 测试依赖
test = [
    "pytest",
    #     "pytest-cov>=4.0.0" # Coverage disabled,
    "pytest-asyncio>=0.21.0",
    "pytest-mock>=3.10.0",
]

[project.urls]
Homepage = "https://github.com/intellistream/SAGE"
Repository = "https://github.com/intellistream/SAGE.git"
Documentation = "https://sage-docs.intellistream.cc"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]
include = ["sage*"]
namespaces = false

# 添加类型信息支持
[tool.setuptools.package-data]
"sage.core" = ["py.typed", "*.pyi"]
"sage.jobmanager" = ["py.typed", "*.pyi"]
"sage.runtime" = ["py.typed", "*.pyi"]

[tool.pytest.ini_options]
testpaths = ["tests", "src"]
python_files = ["test_*.py", "*_test.py"]
addopts = [
    #     "--cov=sage.core" # Coverage disabled,
    #     "--cov=sage.jobmanager" # Coverage disabled,
    #     "--cov=sage.runtime" # Coverage disabled,
    #     "--cov-report=term-missing" # Coverage disabled,
    #     "--cov-report=html" # Coverage disabled,
#    "--cov-report=xml",
]

[tool.black]
line-length = 88
target-version = ["py311"]
include = '\.pyi?$'
extend-exclude = '''
/(
    \.git
    | \.venv
    | build
    | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["sage"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
no_implicit_optional = true
strict_optional = true

[[tool.mypy.overrides]]
module = "sage.core.*"
ignore_missing_imports = false

[[tool.mypy.overrides]]
module = "sage.jobmanager.*"
ignore_missing_imports = false

[[tool.mypy.overrides]]
module = "sage.runtime.*"
ignore_missing_imports = false
