#!/bin/bash
# 自动提交所有子模块的 SUBMODULE.md 文件

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

echo "🚀 自动提交子模块标记文件..."
echo ""

cd "$REPO_ROOT"

# 检查是否有未提交的更改
if [ -n "$(git status --porcelain)" ]; then
    echo "⚠️  警告: 主仓库有未提交的更改"
    echo "建议先提交或暂存这些更改"
    echo ""
    read -p "继续吗? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# 统计
total=0
committed=0
no_changes=0

# 遍历所有子模块 (使用进程替换避免子shell问题)
while IFS= read -r submodule_path; do
    # 确保回到主仓库根目录
    cd "$REPO_ROOT"

    if [ ! -d "$submodule_path" ]; then
        echo "⚠️  跳过: $submodule_path (不存在)"
        continue
    fi

    total=$((total + 1))

    echo "📂 处理子模块: $submodule_path"

    # 进入子模块
    cd "$REPO_ROOT/$submodule_path"

    # 检查是否有 SUBMODULE.md
    if [ ! -f "SUBMODULE.md" ]; then
        echo "   ⚠️  未找到 SUBMODULE.md，跳过"
        continue
    fi

    # 检查是否有更改
    if [ -z "$(git status --porcelain SUBMODULE.md)" ]; then
        echo "   ℹ️  无更改"
        no_changes=$((no_changes + 1))
        continue
    fi

    # 获取当前分支
    branch=$(git config --file "$REPO_ROOT/.gitmodules" --get "submodule.$submodule_path.branch" || echo "main-dev")

    # 确保在正确的分支上
    current_branch=$(git rev-parse --abbrev-ref HEAD)
    if [ "$current_branch" != "$branch" ]; then
        echo "   ⚠️  当前分支: $current_branch, 期望: $branch"
        echo "   切换到 $branch..."
        git checkout "$branch" || {
            echo "   ❌ 无法切换分支，跳过"
            continue
        }
    fi

    # 提交
    git add SUBMODULE.md
    git commit -m "docs: add submodule marker file

This file helps identify this directory as a Git submodule and provides
quick reference for common submodule operations.

Auto-generated by tools/git-tools/generate-submodule-markers.sh" || {
        echo "   ⚠️  提交失败（可能已经提交过）"
        continue
    }

    echo "   ✅ 已提交到本地"

    # 推送到远程
    if git push origin "$branch" 2>&1; then
        echo "   ✅ 已推送到远程"
        committed=$((committed + 1))
    else
        echo "   ⚠️  推送失败，请手动推送"
    fi

    echo ""
done < <(git config --file .gitmodules --get-regexp path | awk '{print $2}')

# 回到主仓库
cd "$REPO_ROOT"

echo "=========================================="
echo "📊 提交摘要"
echo "=========================================="
echo "处理的子模块:   $total"
echo "已提交:         $committed"
echo "无更改:         $no_changes"
echo "=========================================="
echo ""

if [ $committed -gt 0 ]; then
    echo "🔄 更新主仓库的子模块引用..."
    echo ""

    # 显示有更改的子模块
    changed_submodules=$(git status --porcelain | grep "^ M " | grep -o "packages/[^ ]*" || true)

    if [ -n "$changed_submodules" ]; then
        echo "📝 以下子模块有更新:"
        echo "$changed_submodules"
        echo ""

        read -p "提交这些子模块引用更新? (Y/n) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Nn]$ ]]; then
            # 添加所有子模块更改
            git add $(echo "$changed_submodules")

            # 提交
            git commit -m "chore: update submodule references with marker files

Updated submodules:
$changed_submodules

These submodules now include SUBMODULE.md marker files for better
discoverability and developer guidance."

            echo "✅ 已提交主仓库更改"
            echo ""
            echo "💡 提示: 不要忘记推送主仓库:"
            echo "   git push origin main-dev"
        fi
    else
        echo "ℹ️  主仓库无需更新"
    fi
else
    echo "ℹ️  没有子模块被提交"
fi

echo ""
echo "✅ 完成！"
