#!/bin/bash
# 自动为所有 Git 子模块生成 SUBMODULE.md 标记文件

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

echo "🔍 扫描 Git 子模块..."

cd "$REPO_ROOT"

# 检查是否在 git 仓库中
if [ ! -f .gitmodules ]; then
    echo "❌ 错误: 未找到 .gitmodules 文件"
    exit 1
fi

# 统计
total=0
created=0
updated=0
skipped=0

# 遍历所有子模块
while IFS= read -r line; do
    if [[ $line =~ ^\[submodule\ \"(.+)\"\]$ ]]; then
        submodule_name="${BASH_REMATCH[1]}"
    elif [[ $line =~ ^[[:space:]]*path[[:space:]]*=[[:space:]]*(.+)$ ]]; then
        path="${BASH_REMATCH[1]}"
    elif [[ $line =~ ^[[:space:]]*url[[:space:]]*=[[:space:]]*(.+)$ ]]; then
        url="${BASH_REMATCH[1]}"
    elif [[ $line =~ ^[[:space:]]*branch[[:space:]]*=[[:space:]]*(.+)$ ]]; then
        branch="${BASH_REMATCH[1]}"

        # 现在我们有了完整的信息，生成标记文件
        if [ -d "$path" ]; then
            total=$((total + 1))
            marker_file="$path/SUBMODULE.md"

            # 提取仓库名称
            repo_name=$(basename "$url" .git)

            # 计算相对路径回到主仓库
            depth=$(echo "$path" | tr -cd '/' | wc -c)
            back_path=$(printf '../%.0s' $(seq 1 $depth))

            echo ""
            echo "📝 处理子模块: $submodule_name"
            echo "   路径: $path"
            echo "   仓库: $repo_name"
            echo "   分支: ${branch:-main}"

            # 生成标记文件内容
            cat > "$marker_file" << EOF
# Git Submodule: $repo_name

⚠️ **This directory is a Git submodule** - it's a separate repository!

## Repository Information

- **Name:** $submodule_name
- **Repository:** $url
- **Branch:** ${branch:-main}
- **Path:** \`$path\`

## Quick Guide for Committing Changes

### 1️⃣ Commit in This Submodule

\`\`\`bash
# Navigate to this directory (if not already here)
cd $path

# Make your changes, then:
git add .
git commit -m "feat: your change description"
git push origin ${branch:-main}
\`\`\`

### 2️⃣ Update Reference in Main Repository

\`\`\`bash
# Navigate back to main repository root
cd ${back_path}

# Add the submodule reference update
git add $path
git commit -m "chore: update $repo_name submodule reference"
git push origin main-dev
\`\`\`

## Updating This Submodule

To pull latest changes from the submodule repository:

\`\`\`bash
# In this directory
cd $path
git pull origin ${branch:-main}

# Update reference in main repo
cd ${back_path}
git add $path
git commit -m "chore: update $repo_name to latest"
\`\`\`

## Common Issues

### ❌ "fatal: Pathspec ... is in submodule"

**Problem:** You're in the main repository trying to commit submodule files.

**Solution:**
\`\`\`bash
cd $path  # Enter the submodule first
git add .
git commit -m "your message"
\`\`\`

### ❌ Changes not showing in main repository

**Problem:** You committed in the submodule but forgot to update the reference.

**Solution:**
\`\`\`bash
cd ${back_path}  # Back to main repo
git add $path
git commit -m "chore: update $repo_name reference"
\`\`\`

### ❌ "You are not currently on a branch"

**Problem:** Submodule is in detached HEAD state.

**Solution:**
\`\`\`bash
cd $path
git checkout ${branch:-main}
git pull origin ${branch:-main}
\`\`\`

## Development Workflow

1. **Always work on the correct branch:** \`${branch:-main}\`
2. **Commit in submodule first**, then update reference in main repo
3. **Push both repositories** to share your changes
4. **Pull both repositories** when updating

---

📚 For more details, see [CONTRIBUTING.md](${back_path}CONTRIBUTING.md#working-with-submodules)

🤖 This file is auto-generated by \`tools/git-tools/generate-submodule-markers.sh\`
EOF

            if [ -f "$marker_file.bak" ]; then
                updated=$((updated + 1))
                echo "   ✅ 更新: $marker_file"
            else
                created=$((created + 1))
                echo "   ✅ 创建: $marker_file"
            fi
        else
            skipped=$((skipped + 1))
            echo "   ⚠️  跳过: $path (目录不存在)"
        fi

        # 重置变量
        submodule_name=""
        path=""
        url=""
        branch=""
    fi
done < .gitmodules

# 摘要
echo ""
echo "=========================================="
echo "📊 处理摘要"
echo "=========================================="
echo "总子模块数:   $total"
echo "新创建:       $created"
echo "已更新:       $updated"
echo "已跳过:       $skipped"
echo "=========================================="
echo ""

if [ $created -gt 0 ] || [ $updated -gt 0 ]; then
    echo "✅ 成功生成子模块标记文件！"
    echo ""
    echo "📝 下一步:"
    echo "   1. 检查生成的 SUBMODULE.md 文件"
    echo "   2. 在各子模块中提交这些文件:"
    echo "      cd <submodule-path>"
    echo "      git add SUBMODULE.md"
    echo "      git commit -m 'docs: add submodule marker file'"
    echo "      git push origin ${branch:-main-dev}"
    echo ""
    echo "   3. 在主仓库中更新子模块引用:"
    echo "      git add <submodule-path>"
    echo "      git commit -m 'chore: update submodule with marker file'"
    echo ""
    echo "💡 提示: 使用 tools/git-tools/commit-all-submodule-markers.sh 自动提交"
else
    echo "ℹ️  所有子模块标记文件都已是最新"
fi
