[build-system]
requires = [            # 安装构建工具的依赖
    "setuptools>=64",
    "wheel",
    "pybind11>=2.10.0",
    "cmake>=3.18",
    "ninja; platform_system!='Windows'",
    "numpy>=1.21.0",
]
build-backend = "setuptools.build_meta" # 内部会调用setup.py或setup.cfg来完成构建

[project]
name = "sage-extensions"
version = "1.0.0"
description = "SAGE Framework - 高性能C++扩展"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "IntelliStream Team", email = "sage@intellistream.cc"},
]
keywords = ["rag", "llm", "high-performance", "cpp", "extensions"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: C++",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Hardware",
]

dependencies = [
    "sage-core",  # 通过 sage-core 获取 numpy, pybind11 等依赖
    "sage-utils", # 基础工具
    
    # C++扩展构建专用依赖
    "cmake-build-extension>=0.5.0",     # CMake 构建支持
    "setuptools-cpp>=0.1.0",           # C++ setuptools 扩展
]

[project.optional-dependencies]
# 性能分析和基准测试
benchmark = [
    "pytest-benchmark>=4.0.0",
    "memory-profiler>=0.60.0",
    "line-profiler>=4.0.0",
]

# 高性能计算扩展
hpc = [
    "numba>=0.58.0",       # JIT 编译
    "cython>=3.0.0",       # C 扩展优化
]

# 构建时工具（开发时需要）
build-tools = [
    "cmake>=3.18",
    "ninja; platform_system!='Windows'",
    "pybind11-stubgen>=0.10.0",  # 生成类型存根
]

[project.urls]
Homepage = "https://github.com/intellistream/SAGE"
Repository = "https://github.com/intellistream/SAGE.git"
Documentation = "https://sage-docs.intellistream.cc"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]
include = ["sage*"]
namespaces = false

# C++扩展的特殊配置
[tool.setuptools.package-data]
"sage.extensions" = ["*.so", "*.pyd", "*.dll", "py.typed", "*.pyi"]
"sage.extensions.sage_db" = ["*.so", "*.pyd", "*.dll"]


# C++编译配置
[tool.cibuildwheel]
build = "cp311-* cp312-*"
skip = "*-win32 *-manylinux_i686"

[tool.cibuildwheel.environment]
CMAKE_BUILD_TYPE = "Release"

[tool.pytest.ini_options]
testpaths = ["tests", "src"]
python_files = ["test_*.py", "*_test.py"]
addopts = [
    #     "--cov=sage.extensions" # Coverage disabled,
    #     "--cov-report=term-missing" # Coverage disabled,
    #     "--cov-report=html" # Coverage disabled,
#    "--cov-report=xml",
]

[tool.black]
line-length = 88
target-version = ["py311"]
include = '\.pyi?$'
extend-exclude = '''
/(
    \.git
    | \.venv
    | build
    | dist
    | \.pybind11
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["sage"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
# C++扩展可能需要更宽松的类型检查
disallow_untyped_defs = false
no_implicit_optional = true
strict_optional = true

[[tool.mypy.overrides]]
module = "sage.extensions.*"
ignore_missing_imports = true  # C++扩展可能没有类型信息
